FROM node:16.13.0-slim AS frontend

WORKDIR /app/oppia

RUN apt-get update -y && apt-get install -y \
    chromium \
    curl \
    git \
    ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


RUN npm install -g yarn@1.22.15 --force
RUN yarn install --pure-lockfile

# Clean up temporary files
RUN rm -rf /tmp/* /var/tmp/*
